spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qsl
    username: user
    password: 1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 10000      # 10? ?? ? ?? ??
      max-lifetime: 1800000    # 30? ?? ??? ??? ??
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
