# P6Spy ?? ??

# ?? ??? JDBC ???? ??? (?: MySQL, PostgreSQL ?)
realdriver=com.mysql.cj.jdbc.Driver

# ??? ??? ?? (???: System.out)
appender=com.p6spy.engine.spy.appender.StdoutLogger

# ?? ?? (?? ??)
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

# ?? ?? ???
outagedetection=true

# ?? ?? ?? (??)
logfile=spy.log